### PR TITLE
Remove third-party notice for local commands

### LINKED ISSUE #44: 3rd-party command notice message
### Bug Report

|    Q        |   A
|------------ | ------
| Version(s)  | 0.1.3+

#### Summary

In #37 we have added message about executing 3rd party commands.
In my opinion, per https://github.com/laminas/laminas-cli/pull/37#discussion_r463391626 comment, it should not be added for local commands - defined in the project.

We can check local commands by checking namespaces defined in `autoload(-dev)` sections of `composer.json`.

#### Current behavior

We are adding the notice for all non-Laminas commands atm.

#### How to reproduce

Create any local command, use it in a chain and run the command with a chain.

#### Expected behavior

We should skip the message for local commands.

### PR DESCRIPTION
**Pull request by weierophinney**
This patch provides functionality to exclude local commands (defined as anything not in the vendor directory) from resulting in a prompt warning that a third-party command is about to be executed (when executed as part of a chain).

It does so by checking if the command class is defined in the configured Composer `vendor-dir`, but not within a laminas, laminas-api-tools, or mezzio subdirectory. If it is one of those subdirectories, or not defined in the `vendor-dir`, we consider it a local command.

Fixes #44

### CODE REVIEW

File: src/Listener/TerminateListener.php [hunk 1]
```diff
@@ -165,4 +176,50 @@ private function validateInputMap(array $inputMap, string $commandClass): void
...
+        if (! file_exists($autoloadFile)) {
+            return [];
+        }
+
+        /** @psalm-suppress MixedAssignment */
+        $namespaceMap = include $autoloadFile;
+        Assert::isMap($namespaceMap);
+
+        $localNamespaces = [];
+        $vendorDir       = $basePath . '/vendor';
```
Comment (michalbundyra) [inline src/Listener/TerminateListener.php]: It might be not always `vendor`, see:
https://getcomposer.org/doc/06-config.md#vendor-dir

**Review by michalbundyra — COMMENTED** [review]
@weierophinney in general it's fine, but I had a thought about it, and maybe it would be better  (instead of checking the namespace) to check what is the location of the file?

So we would need to show the message if the source file is in vendor but not in:
- vendor/laminas/
- vendor/laminas-api-tools/
- vendor/mezzio/

I think it might be a bit better than checking namespace, because anyone can define any namespace, but I believe noone else is not able to register any `laminas/`, `mezzio/`, `laminas-api-tools/` package.
Also we do not need to care on all cases - PSR-0, PSR-4, files autoloading etc...

Side note: Of course if someone is using `Laminas\` namespace it's wrong, but we do not have too much control on it.

Thoughts?

File: src/Listener/TerminateListener.php (hunk 1 above)
Comment (weierophinney) [reply src/Listener/TerminateListener.php]: Ugh, I always forget that you _can_ do this. I'll update to resolve it.

I've been thinking about your idea, and I think it's likely the more correct path forward. The main problem I have is it's going to be next-to-impossible to test that it detects 3rd party commands correctly, unless we install some as part of our dev dependencies.

Comment (michalbundyra) [reply src/Listener/TerminateListener.php]: I guess we can mock it somehow, in the worst case scenario - create a file in tests in vendor 😱

Comment (weierophinney) [reply src/Listener/TerminateListener.php]: Found a way, using the "Show" command provided with Psalm. :smile:

**Comment by weierophinney** [comment]
@michalbundyra Okay, updated the check for third-party commands such that this now looks to see if the command class is defined within the configured `vendor-dir`, and **is not** in one of the laminas, laminas-api-tools, or mezzio subdirectories.

**Comment by weierophinney** [comment]
I've tested this in an app I maintain, and can confirm:

- I no longer get the "third party command" notice for app-specific commands.
- Chained commands continue to work correctly.
- All of the above is true even when `config.vendor-dir` is configured to another path.

File: src/Listener/TerminateListener.php [hunk 2]
```diff
@@ -165,4 +179,58 @@ private function validateInputMap(array $inputMap, string $commandClass): void
...
+        $basePath     = realpath(getcwd());
+        $composerJson = file_get_contents($basePath . '/composer.json');
+        Assert::string($composerJson);
+
+        $composer = json_decode($composerJson, true);
+        Assert::isMap($composer);
+
+        $vendorDir = $composer['config']['vendor-dir'] ?? $basePath . '/vendor';
+        Assert::string($vendorDir);
+        Assert::directory($vendorDir);
```
Comment (michalbundyra) [inline src/Listener/TerminateListener.php:207]: this might be extreme case, but possible according to composer documentation:

> `$HOME` and `~` will be replaced by your home directory's path

https://getcomposer.org/doc/06-config.md#vendor-dir

File: src/Listener/TerminateListener.php [hunk 3]
```diff
@@ -165,4 +179,58 @@ private function validateInputMap(array $inputMap, string $commandClass): void
...
+
+        $vendorDir = $this->normalizePath(realpath($vendorDir));
+        return rtrim($vendorDir, '/') . '/';
+    }
+
+    /**
+     * @psalm-param class-string $class
+     */
+    private function matchesLocalNamespace(string $class, string $vendorDir): bool
```
Comment (michalbundyra) [inline src/Listener/TerminateListener.php]: I would suggest to change the method name, as we are not matching the vendor dir not the namespace

File: src/Listener/TerminateListener.php [hunk 4]
```diff
@@ -165,4 +179,58 @@ private function validateInputMap(array $inputMap, string $commandClass): void
...
+    private function getVendorDirectory(): string
+    {
+        $basePath     = realpath(getcwd());
+        $composerJson = file_get_contents($basePath . '/composer.json');
+        Assert::string($composerJson);
+
+        $composer = json_decode($composerJson, true);
+        Assert::isMap($composer);
+
+        $vendorDir = $composer['config']['vendor-dir'] ?? $basePath . '/vendor';
```
Comment (michalbundyra) [inline src/Listener/TerminateListener.php:203]: I cannot see any test for custom vendor-dir, so I guess you have checked it manually?

I had an impression first that it might not working first, as it can be relative, but as a fallback we are using fullpath, but noticed then couple lines below realpath on the result, so I believe it's fine :)

**Review by michalbundyra — APPROVED** [review]
@weierophinney Looks good, one comment to suggest method name change and one possible very edge case with custom vendor-dir. Your call if you want to handle these. Thanks

File: src/Listener/TerminateListener.php (hunk 4 above)
Comment (weierophinney) [reply src/Listener/TerminateListener.php:203]: Yeah, had to test it manually, since we resolve the `composer.json` based on the current working directory. I considered a few options for testing, but they all required a lot of bizarre hoops and coding remnants that would have only existed for testing.

When I manually tested, I did so by changing the value of `config.vendor-dir` in an existing project, and having it install my branch as the 0.1.6 release, and then checking how chained commands worked. Prior to the changes in this branch, I got the warning about using 3rd party code; after, the notices were gone.

Comment (weierophinney) [reply src/Listener/TerminateListener.php:203]: Ended up using reflection to test the method, as the change to resolve home paths meant I needed to test those code paths as well.
