### PR TITLE
fix #148 : Add support for symfony/console attribute commands

### LINKED ISSUE #148: Doesn't work with latest symfony/console
### Bug Report

|    Q        |   A
|------------ | ------
| Version(s)  | 1.13.0

#### Current behavior

When using symfony/console with the `AsCommand` attribute, laminas-cli throws an error:
`Command "app:my-command" maps to class "App\MyCommand", which does not extend Symfony\Component\Console\Command\Command`

It incorrectly assumes that a Symfony command needs to extend the `Command` class.

#### How to reproduce

1. Install dependencies, per the readme:

```
composer require laminas/laminas-cli
composer require symfony/console
```

2. Create a basic command, per the [Symfony documentation](https://symfony.com/doc/current/console.html#creating-a-command):

```php
#[AsCommand(name: 'app:my-command')]
final readonly class MyCommand
{
    public function __invoke(): int
    {
        return Command::SUCCESS;
    }
}
```

3. Add configuration, per the readme:

```php
return [
    'laminas-cli' => [
        'commands' => [
            'app:my-command' => MyCommand::class,
        ],
    ],
];
```

3. Run the command, per the readme:

```
vendor/bin/laminas app:my-command
```

#### Expected behavior

A successful execution that exits with 0.

### PR DESCRIPTION
**Pull request by fezfez**

### CODE REVIEW

File: test/TestAsset/AttributCommand.php [hunk 1]
```diff
@@ -0,0 +1,25 @@
...
+namespace LaminasTest\Cli\TestAsset;
+
+use Symfony\Component\Console\Attribute\Argument;
+use Symfony\Component\Console\Attribute\AsCommand;
+use Symfony\Component\Console\Attribute\Ask;
+use Symfony\Component\Console\Command\Command;
+use Symfony\Component\Console\Style\SymfonyStyle;
+
+#[AsCommand(name: 'app:my-command')]
+final readonly class AttributCommand
```
Comment (gsteel) [inline test/TestAsset/AttributCommand.php]: Can you fix the type here `AttributCommand` -> `AttributeCommand`

**Review by gsteel — CHANGES_REQUESTED** [review]

File: test/TestAsset/AttributCommand.php (hunk 1 above)
Comment (fezfez) [reply test/TestAsset/AttributCommand.php]: done

**Review by gsteel — APPROVED** [review]
Thanks @fezfez LGTM 👍
